name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Muddle
        uses: demonnic/build-with-muddler@set_working_dir
        with:
          workingDir: ${{ github.workspace }}/test
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: LusterniaChatTabs
          path: ${{ github.workspace }}/test/build/tmp/
