name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: muddler-version
        uses: pozetroninc/github-action-get-latest-release@v0.5.0
        with:
          owner: demonnic
          repo: muddler
          excludes: prerelease, draft
      
      - uses: actions/checkout@v2
    
      - name: Retrieve muddler
        run: |
          curl -L https://github.com/demonnic/muddler/releases/download/0.5/muddle-shadow-${{ steps.muddler-version.outputs.release }}.tar --output muddler.tar
          mkdir muddler
          tar xf muddler.tar -C muddler-tmp
          mv muddler-tmp/muddler-shadow-${{ steps.muddler-version.outputs.release }} muddler
          rm -rf muddler-tmp
      
      - name: Build package with muddler
        run: |
          muddler/bin/muddle
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: LusterniaChatTabs
          path: build/tmp/
